title: "Ava Welsch's Portfolio"
#logo: "C:\Users\avawe\OneDrive\Pictures\Screenshots\matt-wang-HEiMwutqJrc-unsplash.jpg"
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
